apiVersion: v1
kind: Service
metadata:
  name: http-fun-service
spec:
  selector:
    app: http-fun
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-fun
spec:
  selector:
    matchLabels:
      app: http-fun
  replicas: 2
  template:
    metadata:
      labels:
        app: http-fun
    spec:
      containers:
      - name: http-fun
        image: eaingaran/http-fun:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        lifecycle:
          preStop:
            exec:
              command: ['curl', 'http://localhost:5000/destroy']
      terminationGracePeriodSeconds: 30
